### ISSUE TITLE
Sending friend requests

### ISSUE THREAD

**Issue by kbedoway** [COSC481W-2024Winter/ResoluteApp#11]
**User Story**
As a user, I would like to be able to add new friends so that I can view their fitness activity, they can view mine, and we can interact with each other's tracked exercises.

* **Persona:** June, a new mom and a new user who wants to connect with friends
* **Feature:** Entering a username and sending a friend request to that user
* **Business Value:** Users have the ability to view and interact with their friends' tracked fitness
 
**Tasks**
- [x] Text box to enter username
- [x] "Send" button to send request
- [x] Function to send request to other user
- [x] Ability to recognize if username exists
- [x] Toast message that states request is sent or error
  * "Request sent"
  * "Username not found"

**Acceptance Criteria**
1.  If the user enters an existing username in the textbox and clicks the "Send" button, the entered user will receive the request in their requests collection in the database  
2. If the user enters an nonexistent username in the textbox and clicks the "Send" button, nothing should be sent to the database
3. If the user enters an existing username in the textbox and clicks the "Send" button, there should be a "Request sent" toast message
4. If the user enters a nonexistent username in the textbox and clicks the "Send" button, there should be a "Username not found" toast message
