### ISSUE TITLE
View Exercise Log

### ISSUE THREAD

**Issue by vceci** [COSC481W-2024Winter/ResoluteApp#12]
**User Story**
As a student that is struggling to fit physical activity into my busy schedule and reach fitness goals, I want to be able to view all the exercises I have done in the past to see when I frequently exercise, what exercises I prefer, and if I am meeting my fitness goals.

- Persona: A student who is looking to view past fitness activity
- Feature: A table view that will display all past fitness activity
- Business Value: A user can use their exercise log to see if they are meeting their fitness goals

**Task List**
- [x] create layout for the exercise log using a table view with four columns with text views to display the date, exercise, amount, and unit for each exercise
- [x] fill a collection in FireStore with documents of dummy data
- [x] function to retrieve all logged exercises from the database
- [x] display the exercises in the table 

**Acceptance Criteria**
1. When the "View previous exercise" button is clicked from the home page, the table view should be created an filled on the creation of the view of the exercise log page.
2. The correct exercise information should fill the appropriate columns of the exercise log table.
