### ISSUE TITLE
Viewing inbox messages (friends' exercises)

### ISSUE THREAD

**Issue by dubedo580** [COSC481W-2024Winter/ResoluteApp#15]
**User Story** 
As a new user of the Resolute App, I want to be able to see the exercises that my friends complete and I want them to be able to see mine. This will help me feel more supported in my fitness journey and give me encouragement by seeing how well my friends are doing in theirs. I also want to be able to interact with their exercises so they know that I am supporting them and they have the ability to support me.

- Persona: The full-time student, Emma, who feels more motivated to exercise when encouraged by friends.
- Feature: Viewing the recently logged exercises of a user's friends, and interacting with that log.
- Business Value: Users will feel more connected, as though they are exercising together. 

**Task List**
- [x] add a table view to the page where friend's exercises will be displayed
- [x] the table should have ~~five~~ **four** columns (friend's username, exercise, amount, units, ~~a button to interact~~ **and each row is clickable**)
- [ ] ~~the button should have a thumbs up label, but no current functionality~~
- [x] when the ~~button~~ **row** is clicked, a ~~Toast message can appear that says "Sent" as a test~~ **dialog box prompts the user to send a reply**.
- [x] add a scroll feature to the table

**Acceptance Criteria:**
    1. The table is filled with friend's exercises from a dummy data collection in the database.
    2. When the ~~button~~ **row** is clicked in each table row, a ~~Toast message~~ **dialog** is displayed, indicating that the ~~button~~ **row** was successfully clicked. 
    - **NOTE: AC 1&2 can be tested by the same test**
    3. ~~When the amount of data exceeds what can be displayed on the basic view of the table, the table has the functionality to scroll and show the rest of the data.~~ (**NOT TESTABLE**) 
 **4. Choosing to not send a reply does not delete the selected item from the inbox table**
