### ISSUE TITLE
Connecting app to Firebase Project ResoluteApp

### ISSUE THREAD

**Issue by agentry5** [COSC481W-2024Winter/ResoluteApp#16]
**Description**:
This is a necessary setup issue for all issues assigned to Sprint 1. The Firebase project named ResoluteApp under the Resolute group email in the Firebase console must be associated with the Android project in this repository. As such, steps will be followed from Google's tutorial (https://firebase.google.com/docs/android/setup#:~:text=Open%20the%20Firebase%20Assistant%3A%20Tools,your%20Android%20project%20with%20Firebase.) on connecting our app to our Firebase Project. 

**Task List**:
- [x] Connect the Android project to the appropriate Firebase project
- [x] Attach all necessary Google Services files and dependancies within Android project, so that running the application shows Firebase connection in Logcat.
    - [x] This will involve adding gradle dependencies and plugins for both Firebase and the Firestore database

**Comment by agentry5** [comment]
<img width="1362" alt="Screenshot 2024-02-09 at 12 10 53 AM" src="https://github.com/COSC481W-2024Winter/ResoluteApp/assets/103394643/a9003ff2-cfa4-4123-9425-463100a4ac0e">

Proof of successful Firebase initialization. Included dependencies are: firebase-bom:32.7.1, firebase-analytics, firebase-auth, firebase-firestore.
