### ISSUE TITLE
Opening app while logged in

### ISSUE THREAD

**Issue by agentry5** [COSC481W-2024Winter/ResoluteApp#30]
**User Story**: I like to use Resolute, but it is incredibly inconvenient to have to type in my login credentials every time I want to log my exercises, or encourage my friends for exercising. I want to be able to stay logged into the app, even while offline, and even when the app is closed. 

- **Persona**: Norman, a Chemist who doesn't exercise often, but is already registered for Resolute. 
- **Feature**: When a user has previously logged in without logging out, opening Resolute will bring the user directly to the Home screen, bypassing the need to enter their login information. This includes while the user is offline, and this is done by using SharedPreferences to check if this devices has been used to log in without logging out. 
- **Business Value**: Greatly improved user experience, giving users a reason to use and suggest Resolute as a quick-and-easy way to track their exercises. The faster users can access Resolute, the more those same users will want to keep using Resolute over alternatives. 

**Tasks**:
 - [x] Boolean function in MainActivity.java that checks for the existence of a username and password stored in SharedPreferences.
 - [x] Void function in MainActivity.java that serves the purpose of clearing SharedPreferences.
 - [x] If a user's information is saved in SharedPreferences when the app is opened the user is directly navigated to the home menu.
 - [x] When a user clicks the "logout" button in fragment_profile.xml the function is called to clear SharedPreferences
 - [x] For security purposes, alter the "setUsernameAndPassword" function in MainActivity.java so that a stored password is a "DUMMY" string. Since the password is not used anywhere in the app besides at login, there is no purpose behind storing entered passwords. 

**Acceptance Criteria**:
1. Logging in as a user, closing the app completely, then opening the app leads to the home fragment with no user input. 
2. When logged in, clicking logout, closing the app completely, then opening the app leads to the login screen by default.
