### ISSUE TITLE
Viewing friends list

### ISSUE THREAD

**Issue by kbedoway** [COSC481W-2024Winter/ResoluteApp#31]
**User Story**
As a user, I would like to be able to view my current friends list so that I can see who I am able to interact with and stay up to date with their fitness progress.

* **Persona:** June, a new mom and a new user who wants to connect with friends
* **Feature:** Viewing current friends list
* **Business Value:** Users have the ability to view their current friends
 
**Tasks**
- [x] Function to retrieve data from user's friends collection in Firestore
- [x] Table to display user's current friends with column for username
- [x] Table fills with data from user's friends collection

**Acceptance Criteria**
1. If the user has any current friends, they will be displayed in the table
2. If the user does not have any current friends, nothing will be displayed in the table
