### ISSUE TITLE
Adding SharedPreferences to previous features

### ISSUE THREAD

**Issue by vceci** [COSC481W-2024Winter/ResoluteApp#33]
**User Story**
As a new user of the Resolute App and a full-time student, I want to be using the app in a personalized way. I want to only view my previous exercise and my friend's list, not the data of all users of the app. Being able to only view my data will allow for me to use the app specifically to my needs and allow me to interact with other users.

- Persona: Emma, a full-time student, who wants the Resolute App to be personalized for her only
- Feature: Having the data shown in the Resolute App when Emma is logged in to only be her data (ex. previous exercises and friends list)
- Business Value: This allows for each user to only see their own data for the purpose of personalization and security.

**Task List**
- [x] Each interaction with the database needs to call the getUsername() function to retrieve the user that is currently logged into the app (logging an exercise, viewing previous exercises, sending friend requests).
- [x] When writing to the database, the collection name needs to be updated to include the username of the user currently logged into the app.
- [x] When reading from the database, the collection name needs to be updated to include the username of the user currently logged into the app.
- [x] write testing for this feature

**Acceptance Criteria**
1. When reading from the database, the data that is retrieved and displayed to the screen is only the data belonging to the user that is currently logged into the app.
2. When writing to the database, the only collections that are being edited are the collections that are assigned to the user that is currently logged into the app.
3. If the user does not currently have a collection for that feature, one will be created when there is a write to the database.
4. If the user does not currently have a collection for that feature, no data will be displayed when there is a read from the database.
