### ISSUE TITLE
Friend request page

### ISSUE THREAD

**Issue by dubedo580** [COSC481W-2024Winter/ResoluteApp#34]
**User Story**

Gary Common has downloaded the app and has started logging his exercises. The whole reason he downloaded this app was to get feedback and encouragement from his friends. As of now he has no way to see if his friends have sent any requests or respond to those requests. This feature needs to be implemented so that Gary can truly appreciate the app for what it's meant to be. 

- **Persona:** A current user who has started to log exercises and is awaiting feedback from friends.
- **Feature:** Allow a user to see their incoming friend request and respond to those requests.
- **Business Value:** Without the ability to have friends, this app is little better than a place to store exercises locally. Continued interaction with friends will help keep the app installed and used.

**Tasks**

- [x] A table should be created that generates from a specific users friend request collection
- [x] the user should be able to either accept or deny a friend request from that table via one of two buttons.
- [x] once a user has chosen to either accept or deny any friend requests that request should be cleared from the table

**Acceptance Criteria**

1. The Table should populate with only the specific users Friend Requests.
2. Once the Friend Request has been interacted with it should be removed from the Users Collection
3. The Buttons should move the request to the appropriate collection. A click on Accept User should move that user into the current Users Friends Collection. A click on Deny User should just remove them from the Incoming Requests Collection
