### ISSUE TITLE
Viewing profile information

### ISSUE THREAD

**Issue by agentry5** [COSC481W-2024Winter/ResoluteApp#41]
**User Story**
As a user, I would like to be able to view my profile and change my first name, email, or password whenever I would feel like updating my profile information.

- **Persona:** Kevin, a user who wants to be able to update his profile info whenever he wants
- **Feature:** Able to change user's first name, password, and email
- **Business Value:** Users will have the ability to update their profile information anytime they need to

**Tasks**
- [x] Add a textbox with user's username that is unable to be changed
- [x] Add a textbox with user's first name that is able to be changed
- [x] Add a textbox with user's email that is able to be changed
- [x] Add an "Apply changes" button to send query to database to update user's first name and email and display a toast message that says "User information updated"
- [x] Add a "Change password" button to move to a new ChangePasswordFragment screen
     - [x] Add an "Enter current password" text box
     - [x] Add an "Enter new password" text box
     - [x] Add a "Confirm new password" text box
     - [x] Add an "Apply changes" button to hash new password, send query to database to change user's password, display a toast message that says "Password changed", and navigate back to Home screen fragment

**Acceptance Criteria** 
1. Clicking "Apply changes" while either email or first name fields are empty does not cause changes to take place, and a toast message appears saying "All fields must be filled"
2. Clicking "Apply changes" while email address doesn't contain an "@" symbol does not cause changes to take place, and a toast message appears saying "Email must contain @ symbol"
3. Clicking "Apply changes" while a password field is empty does not cause changes to take place, and a toast message appears saying "All fields must be filled"
4. Clicking "Apply changes" while the new passwords do not match does not cause changes to take place, and a toast message appears saying "New passwords do not match"
