### ISSUE TITLE
Logged exercises get sent to your friends' inbox

### ISSUE THREAD

**Issue by agentry5** [COSC481W-2024Winter/ResoluteApp#44]
**User Story**
A user has successfully registered and added a few of their friends on the app. They've started to log their exercises but have noticed that their friends aren't able to interact with them. Until this feature is implemented, users will not be able to see or interact with their friends exercises. 

**Persona:** A registered user who has been logging exercises successfully and is waiting for feedback from friends
**Feature:** The ability for any user to interact with their specific friends exercises
**Business Value:** Similar to the other business values i've written. It comes down to retention. The point of the app is to get that rush of acknowledgment from friends and family on your accomplishments. Without the interaction its a personal list maker. 

**Tasks**

- [x] After an exercise is logged an identifier for that specific document needs to be obtained and stored
- [x] After that I need obtain a list of all the users current friends
- [x] As i iterate over the friends i'd like to store a reference to that specific exercise in each friends inbox collection
- [x] Implement testing to make sure that the correct exercise shows up in the correct users 

**Acceptance Criteria**

1. Logging an exercise function currently works. Changes made to this function should not change anything related to that.
2. testing needs to be implemented correctly before this is accepted. 
3. The documents stored either need to be a copy of the exact exercise entered
4. when interacted with the document needs to be removed from the friends collection and the table should be updated. The original exercise log should remain untouched.
