### ISSUE TITLE
Seeing friends' responses to logged exercises

### ISSUE THREAD

**Issue by agentry5** [COSC481W-2024Winter/ResoluteApp#45]
**User Story**: 
I exercise with Resolute, and reply to my friends' exercises, but the responses don't seem to do anything. When talking to my friends they claim they aren't receiving my replies. Unless they are able to read my replies, I see no substantial reasons to continue sending replies. 

 - **Persona**: Norman, the chemist who seldom exercises unless alongside friends. He uses Resolute in hopes that he and his friends exercise together more often. 
 - **Feature**: A screen accessible by clicking a previously logged exercise that allows users to see their friends' replies sent from their inboxes to that logged exercise. 
 - **Business Value**: Resolute now has social aspects to its exercise logging, the original vision for the app being realized. Users now feel a sense of community when exercising together with Resolute, so users will end up bringing friends to the app.

**Tasks**:
- [x] Add a new fragment titled "ReplyFragment" that contains a TableLayout nested in a ScrollView, as well as a button labeled "Back". Navigation paths exist between this fragment and PreviousActivityFragment in both directions.
- [x] Dynamically add an onClick() listener to every row added to the PreviousActivityFragment that navigates to this new fragment.
     - [x] The document name of the selected exercise must be shared between fragments, since ReplyFragment needs to run a query using it. Do this using either SharedPreferences or Intents.
- [x] ReplyFragment's TableLayout fills with TableRows containing a single TextView each. These TextViews are the contents of a document in the respective exercise's "replies" collection. Written in form: "[USERNAME] says [REPLY MESSAGE]".
- [x] "Back" button in ReplyFragment navigates to PreviousActivity.

**Acceptance Criteria**:
1. Navigation between PreviousActivity and Reply fragments uses the appropriate exercise document ID between both pages, and the replies are for only this exercise. 
2. If a "replies" sub-collection does not exist for a clicked exercise, the TableLayout simply contains a single row that says "_No replies yet..._" 
3. Inbox_IT.java contains tests that must be written that involve this PBI. Those tests should pass. If they rely on the deletion of an exercise, they can only be linear in function.

Check Inbox_IT.java for necessary test notes.
