### ISSUE TITLE
Removing friends

### ISSUE THREAD

**Issue by kbedoway** [COSC481W-2024Winter/ResoluteApp#48]
**User Story**
As a user, I would like to have the ability to remove friends so I can control who I want to share my fitness progress with. 

* **Persona:** June, a new mom and a new user who wants to track her workouts
* **Feature:** Removing friends
* **Business Value:** Users have the ability to remove friends from their current friends list

**Tasks**
- [x] Ability to remove friend when username in table row is clicked
  * "Remove" button/option
- [x] Function to remove friend from user's friends collection
- [x] Function to remove user from friend's friends collection 
- [x] Toast message that states friend is removed or error
  * "Friend removed"
  * "Friend not removed"

**Acceptance Criteria**
1. If the user clicks a table row of the friends table, a remove option will show
2. If the user clicks the remove option, the friend will be removed from the user's friends collection and the user will be removed from the friend's friends collection.
