### ISSUE TITLE
Make UI design cohesive across all pages

### ISSUE THREAD

**Issue by vceci** [COSC481W-2024Winter/ResoluteApp#56]
**User Story**
I am a new user of Resolute and I want to having the ability to easily read and navigate through the app. I want to see a cohesive design across the different screens that I interact with so that it is visually appealing and easy for me to understand as I learn how to use the app. By having an intentional design, I will be motivated to continue using the app to log my own exercises and engage with the social media aspects of the app.

- Persona: Emma the student, who struggles to find time to exercise, wants to use an exercise app with a clear design so she is not spending a lot of time trying to understand how to use the app
- Feature: Resolute will have a cohesive design across all features of the app, including colors, icons, and text size, to optimize readability and flow
- Business Value: Having a cohesive design allows for Emma to easily engage with Resolute so she is using her time effectively when logging her exercises. She will also be influenced to use the app more, resulting in a more regular fitness routine.

**Task List**
- [x] Add an image to the home screen
- [x] Change overall color scheme of the app to make it unique
- [x] Text sizes and fonts are all readable and cohesive

**Acceptance Criteria**
1. Elements are all viewable and do not overlap
2. Buttons are in similar areas on each screen
3. Color scheme has enough contrast so text can be easily read
