### ISSUE TITLE
Make Exercises Uniform To Users

### ISSUE THREAD

**Issue by dubedo580** [COSC481W-2024Winter/ResoluteApp#59]
**User Story**
Gary Common is back and as usual he's noticed something that could improve the user experience when it comes to the Resolute App. He's been settling in to a routine with his workouts and wishes that he could pull from a list of exercises. 

**Personal:** Any user that regularly uses the application, who gets sick of manually typing in the same exercises to log them
**Feature:** Create a dropdown menu of a set of exercises
**Business Value:** We want the user experience to be as streamlined and user friendly as possible. This enhancement allows the user to limit their time doing to the boring work of 'logging an exercise' and focus more on the important things. The social aspect of it all.

**Tasks**
- [ ] set up code so that when a user is created a collection is stored underneath their user
- [ ] create a set of standard exercises that every user has access to
- [ ] for the xml (interface) add the ability to select a dropdown that displays the standard or default options

**Acceptance Criteria**

1.  The functionality for logging an exercise uniquely already exists. It shouldnt be altered in anyway.
2.  If a user logs using default options all the other fields that are logged behind the scenes should stay the same - we still need access to times logged - username of the individual who logged it etc.
3. I'd like for the documents to be stored as the name of the exercise so we can start to be a little more uniform on documentation
4. ideally the collection would be unique to the user in the form of a collection under the user but if we have to just store a collection with a tag of the user in the main db this would be acceptable for now
