### ISSUE TITLE
Deleting a logged exercise

### ISSUE THREAD

**Issue by kbedoway** [COSC481W-2024Winter/ResoluteApp#65]
**User Story**
As a user, I would like to have the ability to delete an exercise that I previously logged. 

* **Persona:** June, a new mom and a new user who wants to track her fitness
* **Feature:** Deleting a logged exercise
* **Business Value:** Users have the ability to delete a previously logged exercise

**Tasks**
- [x] Add a "Delete exercise" button to the ReplyFragment to delete exercise from PreviousActivityFragment
- [x] Function to delete the exercise from the exercises collection of the current user 
- [x] Function to check if the exercise exists in exercise collection of friend before sending a reply
- [x] Add toast messages that states either "Exercise deleted" or "Exercise not found"

**Acceptance Criteria**
1. If the user clicks the "Delete exercise" button, the exercise is removed from the exercises collection of the current user.
2. When a user sends a reply in the InboxFragment, if the exercise was deleted, do not add the reply to the exercise, but still delete the exercise from the inbox collection of the current user, as though a reply were sent.
